name = "Austere"
author = "cykreet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62496722e7f7241361ba335bd560facc143894940b98936df94fdb07093a0df2"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
