name = "Austere"
author = "cykreet"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25cee78d278ea3c51af1b7369d629bc8f941056f1f838625adb4283e44727085"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
