name = "Austere"
author = "cykreet"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96396b8ff60d1a93edd7172c0981ede38af4528bb9c936f781e051c5b17ff207"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
