name = "Austere"
author = "cykreet"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "893b65ee48f4a38c168ab4c9abe1f99ff53d53cdfaf1b38c1d6002b513c1d143"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
