name = "Austere"
author = "cykreet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4e6570f17a36e49609ecb4fb4ed072b33db15da02ce23eb95fdf9d53f895f91"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
