name = "Austere"
author = "cykreet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20051aa904ec920e8ae610f1d1c8920adcb4c484d8f977d83526abf399ccd5fb"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
