name = "Austere"
author = "cykreet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8633621e3ed020bdcf6141b0629f920dc46ae530a7a22a46bb9cae458a633b8"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
