name = "Austere"
author = "cykreet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "499a56dfffb8c442dd8dc8bfa36b26d42f2ec7c0889f20432db14e83ffed1e44"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
