name = "Austere"
author = "cykreet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12d6a782c51933360798c86fd22ad8ae470c588ce3ea4ed8a01d5a1c0b58d8e7"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
