name = "Austere"
author = "cykreet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9323924a35769a44f2037933d3ca6d3669441155cd1605a5e9b302c5f6f338e"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
