name = "Austere"
author = "cykreet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d8cdaa824b5bbcd55891ff0e3dbc4d45f93d234c35cba871a3e97bc8017db2d"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
