name = "Austere"
author = "cykreet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdf9e67433c9094adadc97c5ab97b3af35f8c4e2278e9e8cf5682abbde9bc9ab"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
