name = "Austere"
author = "cykreet"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16a71726604ef4803e53a73d6d76f7702454eaefbe65e0b41c7b1f89372dbaa6"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
