name = "Austere"
author = "cykreet"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6174419180cfbf46e92aec42085b8dfcff5135a72caadfee3179083e2595518e"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
