name = "Austere"
author = "cykreet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebe095cc2f645594def74190534e583d0c0fd37898c3843af1af16158f7a73a3"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
