name = "Austere"
author = "cykreet"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc4f60c974b5d76e266711cb8b0f8f4c4d98124bd383ae56e74715540caec214"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
